### ISSUE TITLE
Doxygen index page is blank

### ISSUE THREAD

**Issue by evaherrada** [adafruit/Adafruit_Microbit#10]

**Comment by evaherrada** [comment]
@siddacious Is there any special way I need to proceed since this is a fork of someone else's project?
https://github.com/adafruit/Adafruit_Microbit/blob/9a788617e25e81d29c53925681c1ce2e45f24e03/Adafruit_Microbit.cpp#L4-L24

**Comment by siddacious** [comment]
Go ahead as normal but leave the copyright notice and license _content_ as is (except for any `clang-format` changes)

**Comment by evaherrada** [comment]
Linking #11
