### ISSUE TITLE
micro:bit v2 support?

### ISSUE THREAD

**Issue by CSharperMantle** [adafruit/Adafruit_Microbit#16]
I wonder if there's any plan to adapt this library to micro:bit v2 on nRF52. I am currently exploring micro:bit with the Arduino framework and looking a good interop library for them.

**Comment by ladyada** [comment]
https://github.com/adafruit/Adafruit_Microbit/pull/12 said they added it!

**Comment by CSharperMantle** [comment]
Thanks @ladyada for your great response! Closing this.

**Comment by BeauNouvelle** [comment]
Looks like many of the BLE examples do not work. They require that a Soft Device be set, but none appear when using the v2?

**Comment by carlosperate** [comment]
As V2 uses an nRF52833 support for SoftDevice S113 or S140 (https://github.com/sandeepmistry/arduino-nRF5#selecting-a-softdevice) would have to be added to the [arduino-nRF5](https://github.com/sandeepmistry/arduino-nRF5) Arduino core first:
- https://github.com/sandeepmistry/arduino-nRF5#selecting-a-softdevice

**Comment by BeauNouvelle** [comment]
Ah right. Thank you. @carlosperate I may have to find an alternative board in the meantime.

**Comment by tgb20** [comment]
@carlosperate It appears that the arduino-nRF5 library has been abandoned, no updates in over a year. Is there an alternative that the adafruit library could be migrated to? Or perhaps maintain their own that can be updated to accommodate the v2?


I attempted to load the S113 soft device myself but could not find where the `xxaa.ld` files originate from.

**Comment by BeauNouvelle** [comment]
I ended up just buying a dozen ESP32 boards and adding my own sensors. It ended up being cheaper than a micro:bit anyway and the BLE works really well. Loads of docs and source code for that platform.
