### ISSUE TITLE
Arduino/Microbit Tutorial Issue

### ISSUE THREAD

**Issue by kd8bxp** [adafruit/Adafruit_Microbit#3]
Not sure where to report this issue - But this seemed like a good place.
The tutorial is very good https://learn.adafruit.com/use-micro-bit-with-arduino/overview 
- but has missed some steps for installing with a Linux machine.
I ended up following the instructions here https://github.com/sandeepmistry/arduino-nRF5
and that corrected the Linux issues.  It seems like it does work with your current tutorial, but doesn't upload the code to Microbit.
And I think this is the step that fixed the issue for me:
https://github.com/sandeepmistry/arduino-nRF5#flashing-a-softdevice

**Comment by ladyada** [comment]
that is very unusual, the soft device should come on the microbit by default! s110

**Comment by kd8bxp** [comment]
I thought so too... but It maybe worth mentioning it in maybe a "linux troubleshooting" step, it took me a few minutes to figure out what was going on.

**Comment by ladyada** [comment]
i added a halp page here :) https://learn.adafruit.com/use-micro-bit-with-arduino/halp

please advise if something is missing!

**Comment by kd8bxp** [comment]
Looks good too me, Thanks.

**Comment by carlosperate** [comment]
Just for general info, MicroPython does not come with the soft device, so if any MicroPython program has been loaded into the micro:bit, then it would not have it.

**Comment by ladyada** [comment]
ooh good point. ok the makecode example should do it then

**Comment by kd8bxp** [comment]
Ah, that explains why I had problems.... I really wasn't sure  :-) @carlosperate @ladyada thanks for the help and info.
