### ISSUE TITLE
ble_plotter example requires M

### ISSUE THREAD

**Issue by Qqwy** [adafruit/Adafruit_Microbit#4]
I am having trouble running the ble_plotterdemo example:

```
/myfolder/Arduino/libraries/Adafruit_Microbit-master/examples/ble_plotterdemo/ble_plotterdemo.ino:9:21: fatal error: MMA8653.h: No such file or directory
compilation terminated.
exit status 1
Error compiling for board BBC micro:bit.
```

[link to location in repo](https://github.com/adafruit/Adafruit_Microbit/blob/2b9c7f7a79aa1d030d8212f468914a0124742501/examples/ble_plotterdemo/ble_plotterdemo.ino#L9)

Clearly, this header file no longer exists. How to fix this?

**Comment by ladyada** [comment]
https://learn.adafruit.com/use-micro-bit-with-arduino/accelerometer-and-magnetometer
