### ISSUE TITLE
NeoPixel on P4 and above

### ISSUE THREAD

**Issue by joachimhs** [adafruit/Adafruit_Microbit#9]
Hello, 

I have followed the guide here: https://learn.adafruit.com/micro-bit-lesson-3-neopixels-with-micro-bit/software

I can make this work for Pins 0, 1, 2 and 3, but for the pins above this, I am unable to get the NeoPixels to work. 

I am not sure if I need to do some pin-mappings between the PIN numbers and the actual pin-numbers the micro:bit pads are connected to the NRF51 chip? But for P12, I tried both 12 and 20, and neither of these seems to work.

**Comment by ladyada** [comment]
hi - we don't know, we only tried those pins - you may want to chat with some other folks who have done microbit neopixel projects :)
